line-length = 100

exclude = [
    "alembic", 
    ".git",
    "__pycache__",
    "migrations",
    "venv",
    ".venv",
    "build",
    "dist"
]

lint.select = [
  "E",  # pycodestyle (errors)
  "F",  # pyflakes (logic errors, undefined names)
  "B",  # flake8-bugbear (risky patterns)
  "I",  # isort (import sorting)
  "UP", # pyupgrade (auto modernize syntax)
  "C4", # flake8-comprehensions
  "SIM",# flake8-simplify
  "N",  # pep8-naming
  # "D",  # pydocstyle (docstring style)
  "RUF",# Ruff-specific rules,
  "COM", # Trailing comma
  "PTH"
]


lint.ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
  "D107", # Missing docstring in __init__
  "COM812", # warning: The following rule may cause conflicts when used with the formatter: `COM812`. To avoid unexpected behavior, we recommend disabling this rule, either by removing it from the `select` or `extend-select` configuration, or adding it to the `ignore` configuration.
]
