"""Initial schema

Revision ID: 8b28d9959db0
Revises: a7b05eb095de
Create Date: 2025-05-05 17:05:28.841421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b28d9959db0'
down_revision: Union[str, None] = 'a7b05eb095de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_usernames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('discord_username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_usernames_id'), 'discord_usernames', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discord_usernames_id'), table_name='discord_usernames')
    op.drop_table('discord_usernames')
    # ### end Alembic commands ###
