"""
add temp driver grants

Revision ID: 239c8630731f
Revises: e158094ddebd
Create Date: 2026-09-18 23:04:36.845413

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "239c8630731f"
down_revision: str | None = "e158094ddebd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temp_driver_grants",
        sa.Column("discord_user_id", sa.String(), nullable=False),
        sa.Column("discord_username", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("granted_by", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("discord_user_id"),
    )
    op.create_index(
        op.f("ix_temp_driver_grants_expires_at"), "temp_driver_grants", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_temp_driver_grants_expires_at"), table_name="temp_driver_grants")
    op.drop_table("temp_driver_grants")
    # ### end Alembic commands ###
