"""
add slack_forwarded_messages table and flags

Revision ID: 43a03ddfa8a6
Revises: b3f7c2a91d4e
Create Date: 2026-10-04 21:39:32.444618

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43a03ddfa8a6"
down_revision: str | None = "b3f7c2a91d4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_forwarded_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slack_channel_id", sa.String(), nullable=False),
        sa.Column("slack_ts", sa.String(), nullable=False),
        sa.Column("part", sa.Integer(), nullable=False),
        sa.Column("discord_channel_id", sa.String(), nullable=False),
        sa.Column("discord_message_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slack_channel_id", "slack_ts", "part"),
    )
    op.create_index(
        op.f("ix_slack_forwarded_messages_id"), "slack_forwarded_messages", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_slack_forwarded_messages_slack_ts"),
        "slack_forwarded_messages",
        ["slack_ts"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute(
        sa.text(
            "INSERT INTO feature_flags (feature, enabled) "
            "VALUES ('slack_announcements_forwarding', 0), ('slack_announcements_pings', 0)"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        sa.text(
            "DELETE FROM feature_flags WHERE feature IN "
            "('slack_announcements_forwarding', 'slack_announcements_pings')"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_slack_forwarded_messages_slack_ts"), table_name="slack_forwarded_messages"
    )
    op.drop_index(op.f("ix_slack_forwarded_messages_id"), table_name="slack_forwarded_messages")
    op.drop_table("slack_forwarded_messages")
    # ### end Alembic commands ###
