"""
add ask_rides_message_templates

Revision ID: bba96a621366
Revises: c31a8d9eaa85
Create Date: 2026-07-06 11:59:33.334487

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bba96a621366"
down_revision: str | None = "c31a8d9eaa85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_rides_message_templates",
        sa.Column(
            "message_type",
            sa.Enum(
                "wednesday_fellowship",
                "friday_fellowship",
                "sunday_service",
                "sunday_class",
                name="askridesmessagetype",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("message_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ask_rides_message_templates")
    # ### end Alembic commands ###
