"""
add pickup summary settings

Revision ID: e158094ddebd
Revises: c4e9a71d3b80
Create Date: 2026-09-18 16:20:26.197961

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e158094ddebd"
down_revision: str | None = "c4e9a71d3b80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pickup_summary_settings",
        sa.Column("slot", sa.Enum("friday", "sunday", name="pickupsummaryslot"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slot"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pickup_summary_settings")
    # ### end Alembic commands ###
