name: Test

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies
        run: uv sync 

      - name: Run tests with pytest
        run: uv run pytest